name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [
          18.16.x
        ]
        fontawesome-svg-core: [
          1.2.x,
          6.x
        ]
        react-native: [
          latest,
          0.73.x,
          0.72.x,
          0.71.x,
          0.70.x,
          0.69.x,
          0.68.x,
          0.67.x
        ]
        react-native-svg: [
          11.x,
          12.x
        ]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: npm install and test
        run: |
          sudo apt-get install -y jq
          npm install -g npm@9
          npm install
          npm install --no-save --force @fortawesome/fontawesome-svg-core@${{ matrix.fontawesome-svg-core }} react-native@${{ matrix.react-native }}
          export REACT_VERSION=`cat node_modules/react-native/package.json|jq -r .peerDependencies.react`
          npm install --no-save react@${REACT_VERSION} react-dom@${REACT_VERSION} react-test-renderer@${REACT_VERSION}
          npm list --depth 0 react react-dom react-test-renderer react-native-svg || exit 0
          npm run lint
          npm test
